[package]
name = "gostd"
license = "MIT"
version = "0.3.21"
edition = "2018"
authors = ["wandercn<wander@rustpub.com>"]
description = "gostd is the go standard library implementation in rust. gostd 是Go标准库的rust实现"
homepage = "https://github.com/wandercn/gostd"
repository = "https://github.com/wandercn/gostd"
keywords = ["gobind", "go-api", "gostd", "go-to-rust", "go-standard-library"]
categories = ["api-bindings", "accessibility", "development-tools", "compilers"]

[profile.dev]
opt-level = 0

[profile.release]

opt-level = 3
[dependencies]

webpki-roots = "^0.26"
rustls = "^0.23"
gostd_derive = "0.0.3"
gostd_builtin = { version = "^1.0", optional = false, path = "../builtin" }
gostd_time = { version = "^1.0", optional = false, path = "../time" }
rand = "0.8.5"
log = "0.4"
lazy_static = "1.4.0"
bytes = "1"
thiserror ="2.0"
anyhow= "1.0"
